export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const REMOVE_AVATAR = "REMOVE_AVATAR";
export const UPLOAD_BACKGROUND = "UPLOAD_BACKGROUND";
export const REMOVE_BACKGROUND = "REMOVE_BACKGROUND";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
